# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  plan:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # run tests!
      - run:
          name: plan
          command: bundle exec rake plan

  apply:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # run tests!
      - run:
          name: apply
          command: bundle exec rake apply

workflows:
  version: 2
  apply_to_master:
    jobs:
      - apply:
          filters:
            branches:
              only: master
  plan_to_staging:
    jobs:
      - plan:
          filters:
            branches:
              only: /stg\/.+$/
  apply_to_staging_and_plan_to_master:
    jobs:
      - plan:
          requires:
            - apply
          filters:
            branches:
              only: staging
      - apply:
          filters:
            branches:
              only: staging
